function R = rotmat(yaw,pitch,roll)
%Rotation matrix in 3D given tha yaw, pitch and roll of the vector.
%The matrix will rotate the vector by matrix multiplication: xr = R*x,
%where x is the vector to rotate and xr is the outcome.
%
%<yaw>,<pitch> and <roll> specify the angle of rotation in radians
%around the Z-,Y- and X-axes, respectively, of the coordinate system 
%generated by the vector being rotated. The rotation is performed
%counter-clockwise if one looks to the direction pointed by the positive
%end of the corresponding axes.
%
%The notation yaw,pitch and roll comes from the engineering, in particular
%from flight dynamics. Aircrafts, ships etc. are usually described in these
%terms.

R = rotmat_x(roll)*rotmat_y(pitch)*rotmat_z(yaw);

end

function Rx = rotmat_x(theta)

Rx = [1 0 0;
    0 cos(theta) -sin(theta);
    0 sin(theta) cos(theta)];
end

function Ry = rotmat_y(theta)

Ry = [cos(theta) 0 sin(theta);
    0 1 0;
    -sin(theta) 0 cos(theta)];
end

function Rz = rotmat_z(theta)

Rz = [cos(theta) -sin(theta) 0;
    sin(theta) cos(theta) 0;
    0 0 1];
end