function out = lpfg_run(visual,outfl,varargin)
% Wrapper function to run an LPFG model.
% USAGE:
%       OUT = LPFG_RUN(visual,outfl,...)
% OUT is the output structure containing tree object TREE (MATLAB class 'tree'),
% the tree segment struct TS and branching structure BR. These structures
% are inherited from the MATLAB-LIGNUM package (LIGMAT). The geometrical
% and topological information included into these struct's is based on the
% MTG file format generated by the model. 
% NOTE: the OUT struct is only possible if the model generates the output 
% mtg file.
% NOTE: the model must be written in lsystem.l file.
%
% VISUAL - flag whether produce or not the LPFG visualization.
%
% OUTFL - to produce or not the OUT structure. If not, the OUT will be
% empty, i.e. isempty(OUT) == true.
%
% ..,'PARNAME',VALUE,... pairs can be specified to refer to the LPFG model
% model parameters. This interface will write the values through C/C++
% #define statements to the 'user.h' file, which must be read by the model.
% This will overwrite the default parameter values.

% Write the input parameters to the model from varargin
lpfg_set_par('user.h',varargin{:});

% Remove 'out.mtg'
lpfg_set_par('out.mtg');

% The external command to execute. NOTE: lpfg command must be in PATH.
if(visual)
    !lpfg lsystem.l view.v material.mat -q
else
    !lpfg lsystem.l view.v material.mat -b -q
end

if(outfl)
    % Convert the output
    [tr,ts,br] = read_mtg('out.mtg');
    % Form the conventional output struct
    out.tree = tr;
    out.TS = ts;
    out.br = br;
else
    out = [];
end

% Erase constants in 'user.h'
lpfg_set_par('user.h');

end
