function out = lpfg_lgm_run(visual,outfl,varargin)
% Wrapper function to run LPFG LIGNUM model.
% USAGE:
%       OUT = LPFG_LGM_RUN(visual,outfl,...)
% OUT is the output structure containing tree object TREE (MATLAB class 'tree'),
% the tree segment struct TS and branching structure BR. These structures
% are inherited from the MATLAB-LIGNUM package (LIGMAT). The geometrical
% and topological information included into these struct's is based on the
% MTG file format generated by the LPFG-LIGNUM.
%
% VISUAL - flag whether produce or not the LPFG visualization.
%
% OUTFL - to produce or not the OUT structure. If not, the OUT will be
% empty, i.e. isempty(OUT) == true.
%
% ..,'PARNAME',VALUE,... pairs can be specified to refer to the LPFG-LIGNUM
% model parameters. This interface will write the values through C/C++
% #define statements to the 'user.h' file, which is read by the
% LPFG-LIGNUM. This will overwrite the default parameter values.

% Write the input parameters to the model from varargin
lpfg_set_par('user.h',varargin{:});

% Remove 'lignum.mtg'
lpfg_set_par('lignum.mtg');

% The external command to execute. NOTE: lpfg command must be in PATH.
if(visual)
    !lpfg lignum.l view.v material.mat -q
else
    !lpfg lignum.l view.v material.mat -b -q
end

if(outfl)
    % Convert the output
    [tr,ts,br] = read_mtg('lignum.mtg');
    % Form the conventional output struct
    out.tree = tr;
    out.TS = ts;
    out.br = br;
else
    out = [];
end

% Erase constants in 'user.h'
lpfg_set_par('user.h');

end